name: Create Overleaf tarball

on:
  schedule:
    - cron: '0 15 * * 5'
  workflow_dispatch:

jobs:

##########################################################################
# PREPARE
##########################################################################
  
  prepare:
    runs-on: ubuntu-latest
    outputs:
      should_build: ${{ steps.check-version.outputs.should_build }}
      version: ${{ steps.version.outputs.version }}
      commit: ${{ steps.commit.outputs.commit_full }}
    
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Get latest commit
        id: commit
        run: |
          FULL=$(git ls-remote https://github.com/overleaf/overleaf.git HEAD | cut -f1)
          SHORT=${FULL:0:7}
          echo "commit_full=$FULL" >> $GITHUB_OUTPUT
          echo "commit_short=$SHORT" >> $GITHUB_OUTPUT
          
      - name: Clone Overleaf
        run: |
          git clone https://github.com/overleaf/overleaf.git overleaf
          cd overleaf
          git checkout ${{ steps.commit.outputs.commit_full }}

      - name: Get commit date
        id: commit_date
        working-directory: overleaf
        run: |
          COMMIT_DATE="$(git log -1 --format=%cd --date=format:%Y%m%d)"
          echo "commit_date=$COMMIT_DATE" >> $GITHUB_OUTPUT
        
      - name: Define version
        id: version
        run: |
          VERSION="${{ steps.commit_date.outputs.commit_date }}-${{ steps.commit.outputs.commit_short }}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check if tag already exists
        id: check-version
        shell: bash
        run: |
          TAG="${{ steps.version.outputs.version }}"
            # Check in this repo if the tag is already created
            echo "Tag $TAG already exists → skipping build"
            if git ls-remote --tags https://github.com/${{ github.repository }} "$TAG" | grep -q "$TAG"; then
            echo "should_build=false" >> $GITHUB_OUTPUT
          else
            echo "Tag $TAG not found → building"
            echo "should_build=true" >> $GITHUB_OUTPUT
          fi

      # Upload source artefact so we can reuse it in the build step
      - name: Upload source artifact
        if: steps.check-version.outputs.should_build == 'true'
        uses: actions/upload-artifact@v7
        with:
          name: overleaf-source
          path: overleaf
          include-hidden-files: true
          
##########################################################################
# BUILD
##########################################################################

  build:
    needs: prepare
    if: needs.prepare.outputs.should_build == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    env:
      COREPACK_ENABLE_DOWNLOAD_PROMPT: 0
      CI: 1

    steps:
      # Download the prevous uploaded artifact
      - name: Download source
        uses: actions/download-artifact@v4
        with:
          name: overleaf-source
          path: overleaf

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Enable Corepack
        run: corepack enable
          
      - name: Install & compile via genScript.js
        working-directory: overleaf
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: "false"
        run: |
          node server-ce/genScript install | bash
          node server-ce/genScript compile | bash

##########################################################################
# PREPARE TARBALL
##########################################################################

      - name: Prepare release folder
        run: |
          mkdir -p release/services/
          mkdir -p release/libraries/
          mkdir -p release/node_modules/
          mkdir -p release/server-ce/
          mkdir -p release/tools/
          
          cp -r overleaf/services/* release/services/ 
          cp -r overleaf/libraries/* release/libraries/ 
          cp -r overleaf/node_modules/* release/node_modules/ 
          cp -r overleaf/server-ce/* release/server-ce/
          cp -r overleaf/tools/* release/tools/

      - name: Compress tarball
        run: |
          tar -czf overleaf_${{ needs.prepare.outputs.version }}.tar.gz release/

##########################################################################
# RELEASE
##########################################################################

      - name: Publish Release
        uses: softprops/action-gh-release@v2.6.1
        with:
          tag_name: ${{ needs.prepare.outputs.version }}
          name: Overleaf ${{ needs.prepare.outputs.version }}
          files: overleaf_${{ needs.prepare.outputs.version }}.tar.gz
        
